version: '3'
services:

  jenkins:
    image: jenkins:test
    container_name: jenkins
    network_mode: bridge
    # links:
      # - 'gitlabhq:gitlab'
    privileged: true
    user: devops
    volumes:
      - jks_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
      - jks_ws:/var/jenkins_home/workspace
      - jks_caches:/var/jenkins_home/caches
      - jks_jobs:/var/jenkins_home/jobs
      - jks_fps:/var/jenkins_home/fingerprints
    restart: always
    # this httpPort is the reverse port in the ecs instace layer e.g 9090 => nginx's 80
    environment: 
      - JENKINS_OPTS=-Djava.awt.headless=true --prefix=/jenkins --httpPort=8000 --httpListenAddress=0.0.0.0
    depends_on: 
      # - gitlabhq

  nginx:
    image: nginx:1.17.2
    container_name: nginx
    network_mode: bridge
    links:
      - 'jenkins:jenkins'
      # - 'gitlabhq:gitlab'
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    command: nginx-debug -g 'daemon off;'
    ports:
      - '9090:80'
      - '9022:22'
    depends_on: 
      - jenkins
      # - gitlabhq
      
  # gitlabhq:
    # image: 'gitlab/gitlab-ce:latest'
    # container_name: gitlab
    # network_mode: bridge
    # restart: always
    # privileged: true
    # environment: 
      # GITLAB_OMNIBUS_CONFIG: |
        # external_url 'http://localhost/gitlab/'
        # gitlab_rails['registry_enabled'] = false
        # gitlab_rails['sentry_enabled'] = false
        # puma['enable'] = true
        # puma['worker_processes'] = 1
        # sidekiq['max_concurrency'] = 1
        # postgresql['shared_buffers'] = '256MB'
        # postgresql['max_worker_processes'] = 1
        # nginx['enable'] = true
        # nginx['redirect_http_to_https'] = true
        # nginx['worker_processes'] = 1
        # prometheus['enable'] = false
        # alertmanager['enable'] = false
        # node_exporter['enable'] = false
        # redis_exporter['enable'] = false
        # postgres_exporter['enable'] = false
        # gitlab_exporter['enable'] = false
        # grafana['enable'] = false
    # volumes:
      # - etc:/etc/gitlab
      # - dbdata:/var/opt/gitlab
      # - logdata:/var/log/gitlab

volumes:
  # dbdata:
  # logdata:
  # etc:
  jks_caches:
  jks_jobs:
  jks_ws:
  jks_fps:
  jks_home: